# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := Test-lvgl


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += ./Src/lvScreens/lvParameterScreen.o
OBJECTS += ./Src/lvScreens/lvSplashScreen.o
OBJECTS += ./Src/main.o
OBJECTS += ./components/sdio-driver/SDIOBlockDevice.o
OBJECTS += ./components/sdio-driver/TARGET_STM/TARGET_STM32F4/sdio_device.o
OBJECTS += ./components/sdio-driver/util/fsfat_test.o
OBJECTS += ./custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_STM32F407VE_BLACK/PeripheralPins.o
OBJECTS += ./custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_STM32F407VE_BLACK/system_clock.o
OBJECTS += ./custom_targets/TARGET_STM/USBPhy_STM32F407VE.o
OBJECTS += ./libs/Adafruit-GFX-Library/Adafruit_GFX.o
OBJECTS += ./libs/Adafruit-GFX-Library/Adafruit_SPITFT.o
OBJECTS += ./libs/Adafruit-GFX-Library/glcdfont.o
OBJECTS += ./libs/Adafruit_TFTLCD_16bit_STM32-master/src/Adafruit_TFTLCD_16bit_STM32.o
OBJECTS += ./libs/Adafruit_TFTLCD_16bit_STM32-master/src/ili9341.o
OBJECTS += ./libs/Chart/Chart.o
OBJECTS += ./libs/Chart/DataBuffer.o
OBJECTS += ./libs/Chart/DataRecorder.o
OBJECTS += ./libs/Chart/GfxItem.o
OBJECTS += ./libs/Chart/GraphBase.o
OBJECTS += ./libs/Chart/Grid.o
OBJECTS += ./libs/Chart/LineGraph.o
OBJECTS += ./libs/Chart/PlotArea.o
OBJECTS += ./libs/Chart/Scale.o
OBJECTS += ./libs/DHT/DHT.o
OBJECTS += ./libs/Display/touchDriver/touchXPT2046.o
OBJECTS += ./libs/IRSensorD6T/IRSensorD6T.o
OBJECTS += ./libs/Math/PID.o
OBJECTS += ./libs/OneButton/OneButton.o
OBJECTS += ./libs/Radio/RFM69.o
OBJECTS += ./libs/Radio/rfm12.o
OBJECTS += ./libs/Sensors/MAX31865.o
OBJECTS += ./libs/Sensors/RTDAnalog.o
OBJECTS += ./libs/Sensors/Sht31.o
OBJECTS += ./libs/Sensors/VL6180.o
OBJECTS += ./libs/Sensors/i2c.o
OBJECTS += ./libs/Sensors/sht15.o
OBJECTS += ./libs/lvgl/lv_drivers/display/R61581.o
OBJECTS += ./libs/lvgl/lv_drivers/display/SHARP_MIP.o
OBJECTS += ./libs/lvgl/lv_drivers/display/SSD1963.o
OBJECTS += ./libs/lvgl/lv_drivers/display/ST7565.o
OBJECTS += ./libs/lvgl/lv_drivers/display/UC1610.o
OBJECTS += ./libs/lvgl/lv_drivers/display/fbdev.o
OBJECTS += ./libs/lvgl/lv_drivers/display/monitor.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/AD_touch.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/FT5406EE8.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/XPT2046.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/evdev.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/keyboard.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/libinput.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/mouse.o
OBJECTS += ./libs/lvgl/lv_drivers/indev/mousewheel.o
OBJECTS += ./libs/lvgl/lv_drivers/win_drv.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/benchmark/benchmark.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/benchmark/benchmark_bg.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/demo/demo.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/demo/img_bubble_pattern.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/sysmon/sysmon.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/terminal/terminal.o
OBJECTS += ./libs/lvgl/lv_examples/lv_apps/tpcal/tpcal.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_group/lv_test_group.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_misc/lv_test_task.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_obj/lv_test_obj.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_arc/lv_test_arc.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_canvas/lv_test_canvas.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_img/img_flower_icon.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_img/lv_test_img.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_1.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_2.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_3.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_4.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/lv_test_imgbtn.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_label/lv_test_label.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_led/lv_test_led.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_line/lv_test_line.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_list/lv_test_list.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_page/lv_test_page.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_preload/lv_test_preload.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_table/lv_test_table.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_tileview/lv_test_tileview.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_win/lv_test_win.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_stress/lv_test_stress.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_theme/lv_test_theme_1.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tests/lv_test_theme/lv_test_theme_2.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/10_keyboard/lv_tutorial_keyboard.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/1_hello_world/lv_tutorial_hello_world.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/2_objects/lv_tutorial_objects.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/3_styles/lv_tutorial_styles.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/4_themes/lv_tutorial_themes.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/5_antialiasing/apple_icon_alpha.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/5_antialiasing/apple_icon_chroma.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/5_antialiasing/lv_tutorial_antialiasing.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/6_images/flower_icon_alpha.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/6_images/lv_tutorial_images.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/6_images/red_flower.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/6_images/red_rose_16.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/7_fonts/arial_20.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/7_fonts/lv_tutorial_fonts.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/8_animations/lv_tutorial_animations.o
OBJECTS += ./libs/lvgl/lv_examples/lv_tutorial/9_responsive/lv_tutorial_responsive.o
OBJECTS += ./libs/lvgl/porting/lv_port_disp.o
OBJECTS += ./libs/lvgl/porting/lv_port_disp_template.o
OBJECTS += ./libs/lvgl/porting/lv_port_fs_template.o
OBJECTS += ./libs/lvgl/porting/lv_port_indev_template.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_disp.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_group.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_indev.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_obj.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_refr.o
OBJECTS += ./libs/lvgl/src/lv_core/lv_style.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_arc.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_basic.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_img.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_label.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_line.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_rect.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_draw_triangle.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_img_cache.o
OBJECTS += ./libs/lvgl/src/lv_draw/lv_img_decoder.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_fmt_txt.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_roboto_12.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_roboto_16.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_roboto_22.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_roboto_28.o
OBJECTS += ./libs/lvgl/src/lv_font/lv_font_unscii_8.o
OBJECTS += ./libs/lvgl/src/lv_hal/lv_hal_disp.o
OBJECTS += ./libs/lvgl/src/lv_hal/lv_hal_indev.o
OBJECTS += ./libs/lvgl/src/lv_hal/lv_hal_tick.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_anim.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_area.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_async.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_circ.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_color.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_fs.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_gc.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_ll.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_log.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_math.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_mem.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_task.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_templ.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_txt.o
OBJECTS += ./libs/lvgl/src/lv_misc/lv_utils.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_arc.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_bar.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_btn.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_btnm.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_calendar.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_canvas.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_cb.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_chart.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_cont.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_ddlist.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_gauge.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_img.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_imgbtn.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_kb.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_label.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_led.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_line.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_list.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_lmeter.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_mbox.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_objx_templ.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_page.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_preload.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_roller.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_slider.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_spinbox.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_sw.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_ta.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_table.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_tabview.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_tileview.o
OBJECTS += ./libs/lvgl/src/lv_objx/lv_win.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_alien.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_default.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_material.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_mono.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_nemo.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_night.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_templ.o
OBJECTS += ./libs/lvgl/src/lv_themes/lv_theme_zen.o
OBJECTS += ./libs/util/Json.o
OBJECTS += ./libs/util/StopWatch.o
OBJECTS += ./libs/util/cmdb.o
OBJECTS += ./libs/util/dconfig.o
OBJECTS += ./libs/util/jsmn.o
OBJECTS += ./libs/util/statistics.o
OBJECTS += ./libs/util/stepper.o
OBJECTS += ./mbed-os/cmsis/TARGET_CORTEX_M/mbed_tz_context.o
OBJECTS += ./mbed-os/components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.o
OBJECTS += ./mbed-os/components/802.15.4_RF/atmel-rf-driver/source/at24mac.o
OBJECTS += ./mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.o
OBJECTS += ./mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.o
OBJECTS += ./mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.o
OBJECTS += ./mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source/at24mac_s2lp.o
OBJECTS += ./mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.o
OBJECTS += ./mbed-os/components/wifi/esp8266-driver/ESP8266/ESP8266.o
OBJECTS += ./mbed-os/components/wifi/esp8266-driver/ESP8266Interface.o
OBJECTS += ./mbed-os/drivers/source/AnalogIn.o
OBJECTS += ./mbed-os/drivers/source/AnalogOut.o
OBJECTS += ./mbed-os/drivers/source/BusIn.o
OBJECTS += ./mbed-os/drivers/source/BusInOut.o
OBJECTS += ./mbed-os/drivers/source/BusOut.o
OBJECTS += ./mbed-os/drivers/source/CAN.o
OBJECTS += ./mbed-os/drivers/source/DigitalIn.o
OBJECTS += ./mbed-os/drivers/source/DigitalInOut.o
OBJECTS += ./mbed-os/drivers/source/DigitalOut.o
OBJECTS += ./mbed-os/drivers/source/Ethernet.o
OBJECTS += ./mbed-os/drivers/source/FlashIAP.o
OBJECTS += ./mbed-os/drivers/source/I2C.o
OBJECTS += ./mbed-os/drivers/source/I2CSlave.o
OBJECTS += ./mbed-os/drivers/source/InterruptIn.o
OBJECTS += ./mbed-os/drivers/source/InterruptManager.o
OBJECTS += ./mbed-os/drivers/source/MbedCRC.o
OBJECTS += ./mbed-os/drivers/source/PortIn.o
OBJECTS += ./mbed-os/drivers/source/PortInOut.o
OBJECTS += ./mbed-os/drivers/source/PortOut.o
OBJECTS += ./mbed-os/drivers/source/PwmOut.o
OBJECTS += ./mbed-os/drivers/source/QSPI.o
OBJECTS += ./mbed-os/drivers/source/RawSerial.o
OBJECTS += ./mbed-os/drivers/source/ResetReason.o
OBJECTS += ./mbed-os/drivers/source/SPI.o
OBJECTS += ./mbed-os/drivers/source/SPISlave.o
OBJECTS += ./mbed-os/drivers/source/Serial.o
OBJECTS += ./mbed-os/drivers/source/SerialBase.o
OBJECTS += ./mbed-os/drivers/source/SerialWireOutput.o
OBJECTS += ./mbed-os/drivers/source/TableCRC.o
OBJECTS += ./mbed-os/drivers/source/Ticker.o
OBJECTS += ./mbed-os/drivers/source/Timeout.o
OBJECTS += ./mbed-os/drivers/source/Timer.o
OBJECTS += ./mbed-os/drivers/source/TimerEvent.o
OBJECTS += ./mbed-os/drivers/source/UARTSerial.o
OBJECTS += ./mbed-os/drivers/source/Watchdog.o
OBJECTS += ./mbed-os/drivers/source/usb/AsyncOp.o
OBJECTS += ./mbed-os/drivers/source/usb/ByteBuffer.o
OBJECTS += ./mbed-os/drivers/source/usb/EndpointResolver.o
OBJECTS += ./mbed-os/drivers/source/usb/LinkedListBase.o
OBJECTS += ./mbed-os/drivers/source/usb/OperationListBase.o
OBJECTS += ./mbed-os/drivers/source/usb/PolledQueue.o
OBJECTS += ./mbed-os/drivers/source/usb/TaskBase.o
OBJECTS += ./mbed-os/drivers/source/usb/USBAudio.o
OBJECTS += ./mbed-os/drivers/source/usb/USBCDC.o
OBJECTS += ./mbed-os/drivers/source/usb/USBCDC_ECM.o
OBJECTS += ./mbed-os/drivers/source/usb/USBDevice.o
OBJECTS += ./mbed-os/drivers/source/usb/USBHID.o
OBJECTS += ./mbed-os/drivers/source/usb/USBKeyboard.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMIDI.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMSD.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMouse.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMouseKeyboard.o
OBJECTS += ./mbed-os/drivers/source/usb/USBSerial.o
OBJECTS += ./mbed-os/events/source/EventQueue.o
OBJECTS += ./mbed-os/events/source/equeue.o
OBJECTS += ./mbed-os/events/source/equeue_mbed.o
OBJECTS += ./mbed-os/events/source/equeue_posix.o
OBJECTS += ./mbed-os/events/source/mbed_shared_queues.o
OBJECTS += ./mbed-os/features/storage/blockdevice/BufferedBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/ChainingBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/ExhaustibleBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/FlashSimBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/HeapBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/MBRBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/ObservingBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/ProfilingBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/ReadOnlyBlockDevice.o
OBJECTS += ./mbed-os/features/storage/blockdevice/SlicingBlockDevice.o
OBJECTS += ./mbed-os/features/storage/filesystem/Dir.o
OBJECTS += ./mbed-os/features/storage/filesystem/File.o
OBJECTS += ./mbed-os/features/storage/filesystem/FileSystem.o
OBJECTS += ./mbed-os/features/storage/filesystem/fat/ChaN/ff.o
OBJECTS += ./mbed-os/features/storage/filesystem/fat/ChaN/ffunicode.o
OBJECTS += ./mbed-os/features/storage/filesystem/fat/FATFileSystem.o
OBJECTS += ./mbed-os/features/storage/filesystem/littlefs/LittleFileSystem.o
OBJECTS += ./mbed-os/features/storage/filesystem/littlefs/littlefs/lfs.o
OBJECTS += ./mbed-os/features/storage/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += ./mbed-os/features/storage/nvstore/source/nvstore.o
OBJECTS += ./mbed-os/features/storage/system_storage/SystemStorage.o
OBJECTS += ./mbed-os/hal/LowPowerTickerWrapper.o
OBJECTS += ./mbed-os/hal/mbed_critical_section_api.o
OBJECTS += ./mbed-os/hal/mbed_flash_api.o
OBJECTS += ./mbed-os/hal/mbed_gpio.o
OBJECTS += ./mbed-os/hal/mbed_gpio_irq.o
OBJECTS += ./mbed-os/hal/mbed_itm_api.o
OBJECTS += ./mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_lp_ticker_wrapper.o
OBJECTS += ./mbed-os/hal/mbed_pinmap_common.o
OBJECTS += ./mbed-os/hal/mbed_pinmap_default.o
OBJECTS += ./mbed-os/hal/mbed_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v7m.o
OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v8m.o
OBJECTS += ./mbed-os/hal/usb/mbed_usb_phy.o
OBJECTS += ./mbed-os/platform/cxxsupport/mstd_mutex.o
OBJECTS += ./mbed-os/platform/source/ATCmdParser.o
OBJECTS += ./mbed-os/platform/source/CThunkBase.o
OBJECTS += ./mbed-os/platform/source/CallChain.o
OBJECTS += ./mbed-os/platform/source/CriticalSectionLock.o
OBJECTS += ./mbed-os/platform/source/DeepSleepLock.o
OBJECTS += ./mbed-os/platform/source/FileBase.o
OBJECTS += ./mbed-os/platform/source/FileHandle.o
OBJECTS += ./mbed-os/platform/source/FilePath.o
OBJECTS += ./mbed-os/platform/source/FileSystemHandle.o
OBJECTS += ./mbed-os/platform/source/LocalFileSystem.o
OBJECTS += ./mbed-os/platform/source/Stream.o
OBJECTS += ./mbed-os/platform/source/SysTimer.o
OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/mbed_fault_handler.o
OBJECTS += ./mbed-os/platform/source/mbed_alloc_wrappers.o
OBJECTS += ./mbed-os/platform/source/mbed_application.o
OBJECTS += ./mbed-os/platform/source/mbed_assert.o
OBJECTS += ./mbed-os/platform/source/mbed_atomic_impl.o
OBJECTS += ./mbed-os/platform/source/mbed_board.o
OBJECTS += ./mbed-os/platform/source/mbed_critical.o
OBJECTS += ./mbed-os/platform/source/mbed_error.o
OBJECTS += ./mbed-os/platform/source/mbed_error_hist.o
OBJECTS += ./mbed-os/platform/source/mbed_interface.o
OBJECTS += ./mbed-os/platform/source/mbed_mem_trace.o
OBJECTS += ./mbed-os/platform/source/mbed_mktime.o
OBJECTS += ./mbed-os/platform/source/mbed_mpu_mgmt.o
OBJECTS += ./mbed-os/platform/source/mbed_os_timer.o
OBJECTS += ./mbed-os/platform/source/mbed_poll.o
OBJECTS += ./mbed-os/platform/source/mbed_power_mgmt.o
OBJECTS += ./mbed-os/platform/source/mbed_retarget.o
OBJECTS += ./mbed-os/platform/source/mbed_rtc_time.o
OBJECTS += ./mbed-os/platform/source/mbed_sdk_boot.o
OBJECTS += ./mbed-os/platform/source/mbed_semihost_api.o
OBJECTS += ./mbed-os/platform/source/mbed_stats.o
OBJECTS += ./mbed-os/platform/source/mbed_thread.o
OBJECTS += ./mbed-os/platform/source/mbed_wait_api_no_rtos.o
OBJECTS += ./mbed-os/platform/source/mbed_wait_api_rtos.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_armlink_overrides.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_implementation.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_wrapper.o
OBJECTS += ./mbed-os/rtos/source/ConditionVariable.o
OBJECTS += ./mbed-os/rtos/source/EventFlags.o
OBJECTS += ./mbed-os/rtos/source/Kernel.o
OBJECTS += ./mbed-os/rtos/source/Mutex.o
OBJECTS += ./mbed-os/rtos/source/RtosTimer.o
OBJECTS += ./mbed-os/rtos/source/Semaphore.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/mbed_boot.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/mbed_rtos_rtx.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += ./mbed-os/rtos/source/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += ./mbed-os/rtos/source/ThisThread.o
OBJECTS += ./mbed-os/rtos/source/Thread.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_GCC_ARM/startup_stm32f407xx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogin_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogout_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can_legacy.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/system_stm32f4xx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/flash_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/serial_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F4/spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/USBPhy_STM32.o
OBJECTS += ./mbed-os/targets/TARGET_STM/analogin_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/analogout_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/hal_tick_overrides.o
OBJECTS += ./mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_crc_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_overrides.o
OBJECTS += ./mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += ./mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/qspi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/reset_reason.o
OBJECTS += ./mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/serial_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += ./mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/us_ticker.o
OBJECTS += ./mbed-os/targets/TARGET_STM/watchdog_api.o


INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I.././Src
INCLUDE_PATHS += -I.././Src/lvScreens
INCLUDE_PATHS += -I.././components
INCLUDE_PATHS += -I.././components/sdio-driver
INCLUDE_PATHS += -I.././components/sdio-driver/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I.././components/sdio-driver/util
INCLUDE_PATHS += -I.././custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_STM32F407VE_BLACK
INCLUDE_PATHS += -I.././libs
INCLUDE_PATHS += -I.././libs/Adafruit-GFX-Library
INCLUDE_PATHS += -I.././libs/Adafruit-GFX-Library/Fonts
INCLUDE_PATHS += -I.././libs/Adafruit_TFTLCD_16bit_STM32-master
INCLUDE_PATHS += -I.././libs/Adafruit_TFTLCD_16bit_STM32-master/src
INCLUDE_PATHS += -I.././libs/Chart
INCLUDE_PATHS += -I.././libs/DHT
INCLUDE_PATHS += -I.././libs/Display
INCLUDE_PATHS += -I.././libs/Display/touchDriver
INCLUDE_PATHS += -I.././libs/IRSensorD6T
INCLUDE_PATHS += -I.././libs/Math
INCLUDE_PATHS += -I.././libs/OneButton
INCLUDE_PATHS += -I.././libs/Radio
INCLUDE_PATHS += -I.././libs/Sensors
INCLUDE_PATHS += -I.././libs/lvgl
INCLUDE_PATHS += -I.././libs/lvgl/lv_drivers
INCLUDE_PATHS += -I.././libs/lvgl/lv_drivers/display
INCLUDE_PATHS += -I.././libs/lvgl/lv_drivers/indev
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps/benchmark
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps/demo
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps/sysmon
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps/terminal
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_apps/tpcal
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_group
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_misc
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_obj
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_arc
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_bar
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_btn
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_btnm
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_canvas
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_cb
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_chart
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_cont
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_gauge
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_img
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_kb
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_label
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_led
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_line
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_list
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_mbox
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_page
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_preload
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_roller
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_slider
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_sw
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_ta
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_table
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_tabview
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_tileview
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_objx/lv_test_win
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_stress
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tests/lv_test_theme
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/10_keyboard
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/1_hello_world
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/2_objects
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/3_styles
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/4_themes
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/5_antialiasing
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/6_images
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/7_fonts
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/8_animations
INCLUDE_PATHS += -I.././libs/lvgl/lv_examples/lv_tutorial/9_responsive
INCLUDE_PATHS += -I.././libs/lvgl/porting
INCLUDE_PATHS += -I.././libs/lvgl/src
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_core
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_draw
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_font
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_hal
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_misc
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_objx
INCLUDE_PATHS += -I.././libs/lvgl/src/lv_themes
INCLUDE_PATHS += -I.././libs/util
INCLUDE_PATHS += -I.././mbed-os
INCLUDE_PATHS += -I.././mbed-os/cmsis
INCLUDE_PATHS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/components
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/wifi
INCLUDE_PATHS += -I.././mbed-os/components/wifi/esp8266-driver
INCLUDE_PATHS += -I.././mbed-os/components/wifi/esp8266-driver/ESP8266
INCLUDE_PATHS += -I.././mbed-os/drivers
INCLUDE_PATHS += -I.././mbed-os/drivers/internal
INCLUDE_PATHS += -I.././mbed-os/events
INCLUDE_PATHS += -I.././mbed-os/events/internal
INCLUDE_PATHS += -I.././mbed-os/features
INCLUDE_PATHS += -I.././mbed-os/features/storage
INCLUDE_PATHS += -I.././mbed-os/features/storage/blockdevice
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem/fat
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem/fat/ChaN
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem/littlefs
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I.././mbed-os/features/storage/nvstore
INCLUDE_PATHS += -I.././mbed-os/features/storage/nvstore/source
INCLUDE_PATHS += -I.././mbed-os/features/storage/system_storage
INCLUDE_PATHS += -I.././mbed-os/hal
INCLUDE_PATHS += -I.././mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I.././mbed-os/hal/usb
INCLUDE_PATHS += -I.././mbed-os/platform
INCLUDE_PATHS += -I.././mbed-os/platform/cxxsupport
INCLUDE_PATHS += -I.././mbed-os/platform/internal
INCLUDE_PATHS += -I.././mbed-os/platform/source
INCLUDE_PATHS += -I.././mbed-os/platform/source/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/platform/source/minimal-printf
INCLUDE_PATHS += -I.././mbed-os/rtos
INCLUDE_PATHS += -I.././mbed-os/rtos/source
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/device
INCLUDE_PATHS += -I../D:/Projects/Sn/LocalGit/test/Test-lvgl/mbed-os

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= .././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_GCC_ARM/STM32F407XG.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_BOOT_STACK_SIZE=1024


C_FLAGS += -std=gnu11
C_FLAGS += -include
C_FLAGS += ./mbed_config.h
C_FLAGS += -DUSBSTM_HAL_UNSUPPORTED
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DDEVICE_MPU=1
C_FLAGS += -DTARGET_STM32F4
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_NAME=STM32F407VE_BLACK
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1573857414.07
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_STM32F407xE
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_M4
C_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_LPTICKER=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DUSE_FULL_LL_DRIVER
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DDEVICE_USBDEVICE=1
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_FAMILY_STM32
C_FLAGS += -DUSE_HAL_DRIVER
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_STM
C_FLAGS += -DTARGET_STM32F407
C_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DTARGET_STM32F407VE
C_FLAGS += -DTARGET_STM32F407VE_BLACK
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_RESET_REASON=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_WATCHDOG=1
C_FLAGS += -DCOMPONENT_NSPE=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -include
C_FLAGS += ./mbed_config.h
C_FLAGS += -std=gnu11
C_FLAGS += -c
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fno-delete-null-pointer-checks
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -Og
C_FLAGS += -g3
C_FLAGS += -DMBED_DEBUG
C_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
C_FLAGS += -mcpu=cortex-m4
C_FLAGS += -mthumb
C_FLAGS += -mfpu=fpv4-sp-d16
C_FLAGS += -mfloat-abi=softfp

CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += ./mbed_config.h
CXX_FLAGS += -DUSBSTM_HAL_UNSUPPORTED
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DDEVICE_MPU=1
CXX_FLAGS += -DTARGET_STM32F4
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_NAME=STM32F407VE_BLACK
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1573857414.07
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_STM32F407xE
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_LPTICKER=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DUSE_FULL_LL_DRIVER
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DDEVICE_USBDEVICE=1
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_FAMILY_STM32
CXX_FLAGS += -DUSE_HAL_DRIVER
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DTARGET_STM32F407
CXX_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DTARGET_STM32F407VE
CXX_FLAGS += -DTARGET_STM32F407VE_BLACK
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_RESET_REASON=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_WATCHDOG=1
CXX_FLAGS += -DCOMPONENT_NSPE=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -include
CXX_FLAGS += ./mbed_config.h
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -c
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fno-delete-null-pointer-checks
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -Og
CXX_FLAGS += -g3
CXX_FLAGS += -DMBED_DEBUG
CXX_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
CXX_FLAGS += -mcpu=cortex-m4
CXX_FLAGS += -mthumb
CXX_FLAGS += -mfpu=fpv4-sp-d16
CXX_FLAGS += -mfloat-abi=softfp

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DUSE_FULL_LL_DRIVER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DUSBSTM_HAL_UNSUPPORTED
ASM_FLAGS += -DUSE_HAL_DRIVER
ASM_FLAGS += -I..
ASM_FLAGS += -I..\Src
ASM_FLAGS += -I..\Src\lvScreens
ASM_FLAGS += -I..\components
ASM_FLAGS += -I..\components\sdio-driver
ASM_FLAGS += -I..\components\sdio-driver\TARGET_STM\TARGET_STM32F4
ASM_FLAGS += -I..\components\sdio-driver\util
ASM_FLAGS += -I..\custom_targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F407xE\TARGET_STM32F407VE_BLACK
ASM_FLAGS += -I..\libs
ASM_FLAGS += -I..\libs\Adafruit-GFX-Library
ASM_FLAGS += -I..\libs\Adafruit-GFX-Library\Fonts
ASM_FLAGS += -I..\libs\Adafruit_TFTLCD_16bit_STM32-master
ASM_FLAGS += -I..\libs\Adafruit_TFTLCD_16bit_STM32-master\src
ASM_FLAGS += -I..\libs\Chart
ASM_FLAGS += -I..\libs\DHT
ASM_FLAGS += -I..\libs\Display
ASM_FLAGS += -I..\libs\Display\touchDriver
ASM_FLAGS += -I..\libs\IRSensorD6T
ASM_FLAGS += -I..\libs\Math
ASM_FLAGS += -I..\libs\OneButton
ASM_FLAGS += -I..\libs\Radio
ASM_FLAGS += -I..\libs\Sensors
ASM_FLAGS += -I..\libs\lvgl
ASM_FLAGS += -I..\libs\lvgl\lv_drivers
ASM_FLAGS += -I..\libs\lvgl\lv_drivers\display
ASM_FLAGS += -I..\libs\lvgl\lv_drivers\indev
ASM_FLAGS += -I..\libs\lvgl\lv_examples
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps\benchmark
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps\demo
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps\sysmon
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps\terminal
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_apps\tpcal
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_group
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_misc
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_obj
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_arc
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_bar
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_btn
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_btnm
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_canvas
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_cb
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_chart
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_cont
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_ddlist
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_gauge
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_img
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_imgbtn
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_kb
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_label
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_led
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_line
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_list
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_lmeter
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_mbox
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_page
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_preload
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_roller
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_slider
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_sw
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_ta
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_table
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_tabview
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_tileview
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_objx\lv_test_win
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_stress
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tests\lv_test_theme
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\10_keyboard
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\1_hello_world
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\2_objects
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\3_styles
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\4_themes
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\5_antialiasing
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\6_images
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\7_fonts
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\8_animations
ASM_FLAGS += -I..\libs\lvgl\lv_examples\lv_tutorial\9_responsive
ASM_FLAGS += -I..\libs\lvgl\porting
ASM_FLAGS += -I..\libs\lvgl\src
ASM_FLAGS += -I..\libs\lvgl\src\lv_core
ASM_FLAGS += -I..\libs\lvgl\src\lv_draw
ASM_FLAGS += -I..\libs\lvgl\src\lv_font
ASM_FLAGS += -I..\libs\lvgl\src\lv_hal
ASM_FLAGS += -I..\libs\lvgl\src\lv_misc
ASM_FLAGS += -I..\libs\lvgl\src\lv_objx
ASM_FLAGS += -I..\libs\lvgl\src\lv_themes
ASM_FLAGS += -I..\libs\util
ASM_FLAGS += -I..\mbed-os
ASM_FLAGS += -I..\mbed-os\cmsis
ASM_FLAGS += -I..\mbed-os\cmsis\TARGET_CORTEX_M
ASM_FLAGS += -I..\mbed-os\components
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\atmel-rf-driver
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\atmel-rf-driver\atmel-rf-driver
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\atmel-rf-driver\source
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\mcr20a-rf-driver
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\mcr20a-rf-driver
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\source
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\stm-s2lp-rf-driver
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\stm-s2lp-rf-driver\source
ASM_FLAGS += -I..\mbed-os\components\802.15.4_RF\stm-s2lp-rf-driver\stm-s2lp-rf-driver
ASM_FLAGS += -I..\mbed-os\components\wifi
ASM_FLAGS += -I..\mbed-os\components\wifi\esp8266-driver
ASM_FLAGS += -I..\mbed-os\components\wifi\esp8266-driver\ESP8266
ASM_FLAGS += -I..\mbed-os\drivers
ASM_FLAGS += -I..\mbed-os\drivers\internal
ASM_FLAGS += -I..\mbed-os\events
ASM_FLAGS += -I..\mbed-os\events\internal
ASM_FLAGS += -I..\mbed-os\features
ASM_FLAGS += -I..\mbed-os\features\storage
ASM_FLAGS += -I..\mbed-os\features\storage\blockdevice
ASM_FLAGS += -I..\mbed-os\features\storage\filesystem
ASM_FLAGS += -I..\mbed-os\features\storage\filesystem\fat
ASM_FLAGS += -I..\mbed-os\features\storage\filesystem\fat\ChaN
ASM_FLAGS += -I..\mbed-os\features\storage\filesystem\littlefs
ASM_FLAGS += -I..\mbed-os\features\storage\filesystem\littlefs\littlefs
ASM_FLAGS += -I..\mbed-os\features\storage\nvstore
ASM_FLAGS += -I..\mbed-os\features\storage\nvstore\source
ASM_FLAGS += -I..\mbed-os\features\storage\system_storage
ASM_FLAGS += -I..\mbed-os\hal
ASM_FLAGS += -I..\mbed-os\hal\storage_abstraction
ASM_FLAGS += -I..\mbed-os\hal\usb
ASM_FLAGS += -I..\mbed-os\platform
ASM_FLAGS += -I..\mbed-os\platform\cxxsupport
ASM_FLAGS += -I..\mbed-os\platform\internal
ASM_FLAGS += -I..\mbed-os\platform\source
ASM_FLAGS += -I..\mbed-os\platform\source\TARGET_CORTEX_M
ASM_FLAGS += -I..\mbed-os\platform\source\minimal-printf
ASM_FLAGS += -I..\mbed-os\rtos
ASM_FLAGS += -I..\mbed-os\rtos\source
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx4
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5\Include
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5\RTX
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5\RTX\Config
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5\RTX\Include
ASM_FLAGS += -I..\mbed-os\rtos\source\TARGET_CORTEX\rtx5\RTX\Source
ASM_FLAGS += -I..\mbed-os\targets\TARGET_STM
ASM_FLAGS += -I..\mbed-os\targets\TARGET_STM\TARGET_STM32F4
ASM_FLAGS += -I..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F407xE
ASM_FLAGS += -I..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F407xE\device
ASM_FLAGS += -I..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\device
ASM_FLAGS += -ID:\Projects\Sn\LocalGit\test\Test-lvgl\mbed-os
ASM_FLAGS += -include
ASM_FLAGS += .\mbed_config.h
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -c
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fno-delete-null-pointer-checks
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -Og
ASM_FLAGS += -g3
ASM_FLAGS += -DMBED_DEBUG
ASM_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
ASM_FLAGS += -mcpu=cortex-m4
ASM_FLAGS += -mthumb
ASM_FLAGS += -mfpu=fpv4-sp-d16
ASM_FLAGS += -mfloat-abi=softfp


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_BOOT_STACK_SIZE=1024 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "$(filter %.o, $^)" > .link_options.txt
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ @.link_options.txt $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
